### PR TITLE
protoc gen support complex directory

### PR DESCRIPTION
**Pull request by tsingsun**
If your project organization directory is more complex, such as the Ent schema directory and the target directory and proto directory are separate. ent proto is not support it. the new PR resolver it

like such as:
```
- api
- - proto    // ent proto generated file
- ent          // ent generated
- graph
- - schma    // the ent schema
```

### CODE REVIEW

**Comment by tsingsun** [comment]
the generate.go will be

```
//go:generate protoc -I=.. --go_out=.. --go-grpc_out=.. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --entgrpc_out=.. --entgrpc_opt=paths=source_relative,schema_path=../../../graph/entgen/schema,ent_package=github.com/woocoos/knockout/ent entpb/entpb.proto
```
entgrpc_opt :

schema_path: now will auto generate the wright relative path between generate.go path and schema path.
ent_package: for protoc-gen-entgrpc can solver ent package

**Comment by tsingsun** [comment]
@rotemtam can you help review this PR?

**Review by rotemtam — COMMENTED** [review]
Hey @tsingsun 

Apologies for taking long to respond. I'm in favour of allowing fine grained control over where the code is generated to.
In terms of the API, I've been wanting for a while to make entproto compliant with the Extension API, and I feel that instead if it's own method, this should be a functional option on that extension.
I will send a PR for it soon

**Comment by rotemtam** [comment]
@tsingsun please review: https://github.com/ent/contrib/pull/462 , does this achieve what you need?

**Comment by tsingsun** [comment]
@rotemtam good job!! but found below problem

1. Rel will cause error if absolute path and relative path,so[extension-L151](https://github.com/ent/contrib/blob/ecbb9cd4a59c36f743e533148a4f78d35963dcc1/entproto/extension.go#L151)
```
			toBase, err := filepath.Rel(abs, g.Config.Target)
```
fix:
```
                       tabs, err := filepath.Abs(g.Config.Target)
			if err != nil {
				return fmt.Errorf("entproto: failed generating generate.go file for %q: %w", g.Config.Target, err)
			}
			toBase, err := filepath.Rel(abs, tabs)
```
2. protol option go_package
```
option go_package = "entgo.io/contrib/entproto/internal/altdir/ent/proto/entpb"; // miss v1 dir
```
3. generate protoc no support Ent Target and Ent schema in different root dir
```
- ent
- schema
```

```
//go:generate protoc -I=.. --go_out=.. --go-grpc_out=.. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --entgrpc_out=.. --entgrpc_opt=paths=source_relative,schema_path=../../../schema entpb/entpb.proto
```
generate.go only schema_path,no ent target package. grpc-go-entproto can't find the `entc` generate package

**Comment by tsingsun** [comment]
@rotemtam have commit and refresh this PR done. please review

**Comment by KaptinLin** [comment]
entproto: failed generating protos: entproto: failed generating generate.go file for "proto\\entpb\\entpb.proto": Rel: can't make  relative to

**Pull request closed without merging**
