### PR TITLE
#2479 entproto fix - removed 'return nil, nil' from method_get.tmpl

### PR DESCRIPTION
**Pull request by thmeitz**

### CODE REVIEW

**Comment by rotemtam** [comment]
https://github.com/ent/contrib/tree/master/entproto#contributing

CI is red, see:

https://github.com/ent/contrib/tree/master/entproto#contributing

**Comment by thmeitz** [comment]
> CI is red, see:
> 
> https://github.com/ent/contrib/tree/master/entproto#contributing

I'm using protoc `libproto 3.20.0`. Since I have problems with the apt package on my Ubuntu box, I manually installed the latest protoc version.

For this reason it will not make sense to run generate.

**Comment by rotemtam** [comment]
Still, CI will fail since it generates everything and checks that Git is clean and we cannot merge unless it's green.

 Check the README for instructions for running in Docker to simulate the CI environment if you have issues in your local box

**Comment by thmeitz** [comment]
The readme file contains errors

```
docker run -it -v $(pwd):/go/src -w /go/src/entproto entproto bash
```
must be
```
docker run -it -v $(pwd):/go/src -w /go/src/entproto entproto-dev bash
```

**Comment by rotemtam** [comment]
Good point, thanks!

**Review by rotemtam — APPROVED** [review]
Well done, thanks for your contribution!

**Pull request merged**
