### PR TITLE
entgql: Conditionally include orderBy argument in connection field

### PR DESCRIPTION
**Pull request by scraymondjr**
In working off latest tip I discovered that the connection query fields were always being generated with the `OrderBy` argument referencing an OrderBy type for the node type. This produces invalid graphql schema in the case that no OrderBy type exists for the node type. A quick fix for this is to check if any OrderBy fields are specified and `SkipOrderField` is not set for the type and pass the result of this check to `ConnectionField` method. This same check needs to be applied at both usages of `ConnectionField` - in building the schema for a node and building the edges for the node.

### CODE REVIEW

**Comment by scraymondjr** [comment]
Creating this PR before writing tests to check if this change is valid. Would appreciate a sanity check that this issue does in fact need to be addressed and then will happily add test coverage to complete the PR.

**Comment by giautm** [comment]
Hey, thank @scraymondjr for this PR. I will include this change in https://github.com/ent/contrib/pull/305, because we need to update the Go template too.

**Comment by giautm** [comment]
Hello @scraymondjr, can you try this branch to verify your issue? https://github.com/ent/contrib/pull/305

**Comment by scraymondjr** [comment]
Hey @giautm I tried with the latest commit in contrib and it looks like this is fixed! Thank you.

**Pull request closed without merging**
