### PR TITLE
Privatize columns used in cursors predicates

### PR DESCRIPTION
**Pull request by amrnt**

### CODE REVIEW

**Review by a8m — COMMENTED** [review]
PR looks good, I don't see any problems merging this. But are you able to reproduce this somehow with a test or just elaborate where does it fail?

**Comment by amrnt** [comment]
Using multi order, It does fail when for instance having `Paginate`  chained to `Modify` with joins for example, and the order fields does exist in both (or more) tables.

The error was eg:
```
panic: [{"message":"ambiguous column name: status","path":["todosWithJoins"]}]
```

I added a test case

**Comment by amrnt** [comment]
@a8m does the latest push satisfies the PR?

**Review by a8m — APPROVED** [review]
💯 

Thanks, @amrnt.

**Pull request merged**
