### PR TITLE
entproto: support enum values with special characters

### PR DESCRIPTION
**Pull request by jamslinger**
This fixes: https://github.com/ent/ent/issues/3498

### CODE REVIEW

**Review by rotemtam — CHANGES_REQUESTED** [review]
I like this . Please handle the case of two enums that normalize to a identical string with an informative error?

**Comment by jamslinger** [comment]
> I like this . Please handle the case of two enums that normalize to a identical string with an informative error?

Thanks for your feedback, that's a good point. I assume you mean two values within a single enum right? I updated the PR accordingly and also added a test.

I also factored out a [`entproto.NormalizeEnumIdentifier`](https://github.com/jamslinger/contrib/blob/enum-value-normalization/entproto/enum.go#L142) function so that we don't rely on the same normalization logic being implemented in multiple different places. It is still being defined twice though, in `entproto.NormalizeEnumIdentifier` as well as in [the enum template](https://github.com/jamslinger/contrib/blob/enum-value-normalization/entproto/cmd/protoc-gen-entgrpc/template/enums.tmpl#L11).

I also have a question: We are not being consistent in error messages with strings vs. quoted strings and I assume we are stuck with this for backwards compatibility?

**Review by rotemtam — APPROVED** [review]
Thanks for the contribution @jamslinger !

**Comment by rotemtam** [comment]
@jamslinger CI is red, can you check ?

**Comment by jamslinger** [comment]
I did a `go mod tidy` and it should be fixed now.

**Comment by rotemtam** [comment]
Thanks for the contribution @jamslinger !

**Comment by jamslinger** [comment]
Thanks for the support @rotemtam :)

**Pull request merged**
