### PR TITLE
fix(entgql): panic caused by nil graphql field context.

### PR DESCRIPTION
**Pull request by hsblhsn**
Closes ent/ent#2946

### CODE REVIEW

**Comment by giautm** [comment]
@hsblhsn, please update the generated code by run `go generate ./...` in the `entgql` directory

**Comment by hsblhsn** [comment]
Hi @giautm, I have generated the code. And there has some version mismatch for `protoc` and `protoc-gen-go` between my machine and ent repository (see changes at `entproto/internal/todo/ent/proto/entpb/entpb.pb.go`). Is there any contribution guide to pin to exact version?

Thanks :)

**Comment by giautm** [comment]
> Hi @giautm, I have generated the code. And there has some version mismatch for `protoc` and `protoc-gen-go` between my machine and ent repository (see changes at `entproto/internal/todo/ent/proto/entpb/entpb.pb.go`). Is there any contribution guide to pin to exact version?
> 
> Thanks :)

you should run the command inside the entgql directory, that is not required other tools (like protobuf)

**Comment by a8m** [comment]
As I wrote in the Ent issue tracker, this code is generated for the gqlgen integration and one of the expectations is a correct context.

**Comment by a8m** [comment]
Thanks for the contribution @hsblhsn, it’s appreciated even though it was not merged 🙏🏻

**Pull request closed without merging**
